### ISSUE TITLE
VM extension 'Microsoft.Compute' and type 'DependencyAgentWindows' could not be found 

### ISSUE THREAD

**Issue by Goatlord0899** [Azure/azure-storage-av-automation#17]
Hello Team,
We are in the process of deploying this antivirus solution, However, we are facing some deployment issues with the solution. The pipeline is generating an error message that reads "ArtifactNotFound: The VM extension with publisher 'Microsoft.Compute' and type 'DependencyAgentWindows' could not be found."

Although we have updated the code with the latest version and publisher of the Dependency, the issue still persists. We are curious if anyone has encountered a similar error or has successfully deployed this solution.

Any guidance would be appreciated

**Comment by t-ashitrit** [comment]
Hello @Goatlord0899,
Can you please share more details about your deployment process?
In which method you are trying to deploy this solution? (ARM template/script)

**Comment by Goatlord0899** [comment]
we are using Azure DevOps to deploy this code and we have managed to clone the git repo, we have then managed to create variables for the requires services to be deployed and are using a yaml file which points to the .ps1 script

**Comment by t-ashitrit** [comment]
I took another look at the ARM templates and I'm sure that there is no usage of 'DependencyAgentWindows' compute extension.
The only one I'm using is 'CustomScriptExtension'.
I think that your problem is not related to this repo but to the infrastructure you are using to deploy it.
Closing this issue but feel free to reopen it if you think otherwise.
