### ISSUE TITLE
Is this a recommended production ready approach for doing Antivirus scanning in Azure blobs?

### ISSUE THREAD

**Issue by manikandanramaswami** [Azure/azure-storage-av-automation#2]
Please advice if this is a recommended production ready approach for doing near realtime antivirus scanning in Azure blobs?

**Comment by t-ashitrit** [comment]
This is a community repo of code and resources you'll be deploying in your own environment, we built it with production scenarios in mind, and they should be deployed at your responsibility.

In order to make sure this architecture and code are in line with your standards in production, please review the code and the architecture before deployment. Because this is a template, you can see the underlying resources.

The only code that you cannot review is the Microsoft Defender Antivirus, which we guarantee is production ready.
