### ISSUE TITLE
Retrieve Blob in Scanner VM rather than streaming from Azure Function

### ISSUE THREAD

**Issue by manikandanramaswami** [Azure/azure-storage-av-automation#4]
Please advice if it would be a better idea (or) any performance gain if we just send the blob name reference to Scanner service running in VM, so that it can download from blob and return result rather than streaming the blob from function to VM. Will this approach work better if have to deal with large file size (let's say 1 GB file) getting uploaded to the blob?

**Comment by t-ashitrit** [comment]
Downloading blobs from the storage account directly:
Using your suggested approach would increase performance for large size files but with a few comments:
* It can lead to a security flaw if not configured correctly since the VM (That potentially can contain malware for a short time) has now access directly to the storage account.
* The download speed is limited by the VM bandwidth so in case multiple large files are downloaded together the performance gain could be smaller.

If you do want to implement that approach I would advise you to use Managed Identity and grant the VM identity access to the storage account only to Read content from the account.

Let me know if you need more information

**Comment by manikandanramaswami** [comment]
Thanks for the response. Using Managed identity with read-only access to storage seems to be a way forward idea with great security and good performance yield.
